name: AchievementHunt
version: '${project.version}'
main: me.chrisx97.achievementhunt.AchievementHunt
api-version: '1.20'
commands:
  start:
    description: starts the game

  stopgame:
    description: stops the game

  achievementhunt:
    description: opens the achievement gui
    aliases: [ah, ahunt, hunt]