name: AchievementHunt
version: '${project.version}'
main: me.chrisx97.achievementhunt.AchievementHunt
api-version: '1.20'
commands:
  goals:
    description: opens the goals GUI

  achievementhunt:
    description: base command
    aliases: [ah, ahunt, hunt]